fastlane_version "2.157"
default_platform :ios

platform :ios do 

    desc "Build iOS app"
    lane :build do
        build_app(
            derived_data_path: "/Users/setuper/Library/Developer/Xcode/DerivedData",
            workspace: 'ChatClient.xcworkspace',
            scheme: 'ChatClient',
            clean: false,
            silent: true,
            skip_codesigning: true,
            skip_profile_detection: true,
            skip_package_ipa: true,
            skip_archive: true
        )
    end
end